# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '29th_Assign_Youtube_Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 29th_Assign_Youtube_Clone
  pod 'SnapKit'
  pod 'Then'
  pod 'Alamofire'
end
